### ISSUE TITLE
Exercises about refactoring

### ISSUE THREAD

**Issue by hankturowski** [exercism/x-common#94] opened 2015-06-20 00:23 UTC
I recently used the [Gilded Rose](https://github.com/emilybache/GildedRose-Refactoring-Kata) refactoring exercise in a group I meet with locally and it was a big hit. I'd like to add it as an exercise here, but I'm not sure how it will fit. The problem is given as an existing (and very ugly) code base for a store's inventory system and it needs to be updated to support a new item type.

The user is supposed to refactor away from a convoluted set of if/else statements to an object oriented solution, then add the new item type. The repository I linked to above has versions in many, many languages.

I have two questions:

First, are there any issues with adding this exercise to exercism.io? I've ported the code to a new language, so I won't be directly importing someone else's work verbatim, but I'm also not the original author.

Second, because the exercise take the form of an existing code base, it's not enough to download a test suite (in fact, not having a test suite to start from is a better exercise). Does the current system support this kind of problem?

**Comment by Dog** [comment] 2015-06-20 06:04
I had a draft of a problem I think is similar to what you are suggesting. It was intended to be a multi step exercise where each segment asked you meet the specification of a client. Each would ask you to build upon previous functionality and/or change functionality. I didn't see any feedback on it though.

https://gist.github.com/Dog/a257729d6c2e99b6685a

**Comment by kytrinyx** [comment] 2015-06-20 06:46
The system does support this. Do you know if there's a license on the exercise?

**Comment by hankturowski** [comment] 2015-06-20 11:26
[The original version](https://github.com/NotMyself/GildedRose) was published under the MIT license.

**Comment by kytrinyx** [comment] 2015-06-20 15:21
Perfect. That's what we're using for all the exercises, so provided that we have proper attribution, this should be fine.

**Comment by hankturowski** [comment] 2015-06-20 15:24
Great. Do I need to do anything special to get it in place, or just drop the starting file and description in like any other exercise?

**Comment by kytrinyx** [comment] 2015-06-20 15:27
There are a couple of dependencies that need to be in place, described here: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#submitting-new-problems

Let me know if you have any questions.

**Comment by kytrinyx** [comment] 2016-04-07 02:22
@hankturowski It's been a while; is this something you're still interested in pursuing?

**Comment by kytrinyx** [comment] 2016-05-31 15:22
I've summarized this issue briefly in the new refactoring exercises conversation in the discussions repository (https://github.com/exercism/discussions/issues/24). I'm going to close this issue and let it live on over in discussions.

**Closed by kytrinyx** 2016-05-31 15:22 UTC
Labels: discussion
