### ISSUE TITLE
Write Docs on how to extract test data

### ISSUE THREAD

**Issue by scottwhudson** [exercism/x-common#315] opened 2016-08-01 20:29 UTC
The section about [how to extract shared test data](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data) is currently empty, but there are a ton of open tickets on doing this for exercises.

Would someone with experience doing this type of ticket mind writing up some docs on how to do this?

**Comment by kytrinyx** [comment] 2016-08-01 21:05
💯 I'd love it if someone who has done a few of these would take a stab at writing up how they did it.

We have an open issue for this with some discussion: https://github.com/exercism/x-common/issues/230

@behrtam @IanWhitney @soniakeys @petertseng @mikeyjcat if any of you have some time to put together some pointers about how you went about extracting data, that would be stellar.

I'm going to close this as a duplicate of #230

**Closed by kytrinyx** 2016-08-01 21:05 UTC
